[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "on_failure"
startCommand = "npm run start:railway"

[services.variables]
NODE_ENV = "production"
FRONTEND_URL = "https://mo-s-burrito-app-production.up.railway.app"

[environments.production]
variables = {}

[volumes]
uploads = "/app/uploads"